#!/usr/bin/env bash

echo "
===================
| Running ktlintFormat
===================
"
./gradlew ktlintFormat

echo "
===================
|  Running ktlintCheck...
===================
"
./gradlew --no-daemon --stacktrace -PdisablePreDex ktlintCheck

checkStyleStatus=$?

[ $checkStyleStatus -ne 0 ] && exit 1

echo "
===================
|  Running lint
===================
"
if [ -z "$dirToLint" ]
  then
  dirToLint="."
fi

./gradlew lint

lintStatus=$?

[ $lintStatus -ne 0 ] && exit 1

exit 0